/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppVitalsRouteImport } from './routes/_authenticated/app.vitals'
import { Route as AuthenticatedAppTodayRouteImport } from './routes/_authenticated/app.today'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated/app.templates'
import { Route as AuthenticatedAppSessionsRouteImport } from './routes/_authenticated/app.sessions'
import { Route as AuthenticatedAppRacesRouteImport } from './routes/_authenticated/app.races'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppNoticeboardRouteImport } from './routes/_authenticated/app.noticeboard'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/app.messages'
import { Route as AuthenticatedAppDailyLogRouteImport } from './routes/_authenticated/app.daily-log'
import { Route as AuthenticatedAppCheckoutRouteImport } from './routes/_authenticated/app.checkout'
import { Route as AuthenticatedAppAthletesRouteImport } from './routes/_authenticated/app.athletes'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppSessionsIndexRouteImport } from './routes/_authenticated/app.sessions.index'
import { Route as AuthenticatedAppRacesIndexRouteImport } from './routes/_authenticated/app.races.index'
import { Route as AuthenticatedAppCoachIndexRouteImport } from './routes/_authenticated/app.coach.index'
import { Route as AuthenticatedAppAthletesIndexRouteImport } from './routes/_authenticated/app.athletes.index'
import { Route as ApiPublicHooksRunDailyRemindersRouteImport } from './routes/api/public/hooks/run-daily-reminders'
import { Route as ApiPublicHooksDispatchPushRouteImport } from './routes/api/public/hooks/dispatch-push'
import { Route as AuthenticatedAppSessionsNewRouteImport } from './routes/_authenticated/app.sessions.new'
import { Route as AuthenticatedAppSessionsCalendarRouteImport } from './routes/_authenticated/app.sessions.calendar'
import { Route as AuthenticatedAppSessionsSessionIdRouteImport } from './routes/_authenticated/app.sessions.$sessionId'
import { Route as AuthenticatedAppRacesRaceIdRouteImport } from './routes/_authenticated/app.races.$raceId'
import { Route as AuthenticatedAppCoachSlugRouteImport } from './routes/_authenticated/app.coach.$slug'
import { Route as AuthenticatedAppAthletesAthleteIdRouteImport } from './routes/_authenticated/app.athletes.$athleteId'
import { Route as AuthenticatedAppSessionsSessionIdIndexRouteImport } from './routes/_authenticated/app.sessions.$sessionId.index'
import { Route as AuthenticatedAppRacesRaceIdIndexRouteImport } from './routes/_authenticated/app.races.$raceId.index'
import { Route as AuthenticatedAppSessionsSessionIdAnalysisRouteImport } from './routes/_authenticated/app.sessions.$sessionId.analysis'
import { Route as AuthenticatedAppRacesRaceIdAnalysisRouteImport } from './routes/_authenticated/app.races.$raceId.analysis'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVitalsRoute = AuthenticatedAppVitalsRouteImport.update({
  id: '/app/vitals',
  path: '/app/vitals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTodayRoute = AuthenticatedAppTodayRouteImport.update({
  id: '/app/today',
  path: '/app/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/app/templates',
    path: '/app/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSessionsRoute =
  AuthenticatedAppSessionsRouteImport.update({
    id: '/app/sessions',
    path: '/app/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRacesRoute = AuthenticatedAppRacesRouteImport.update({
  id: '/app/races',
  path: '/app/races',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppNoticeboardRoute =
  AuthenticatedAppNoticeboardRouteImport.update({
    id: '/app/noticeboard',
    path: '/app/noticeboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/app/messages',
    path: '/app/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDailyLogRoute =
  AuthenticatedAppDailyLogRouteImport.update({
    id: '/app/daily-log',
    path: '/app/daily-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCheckoutRoute =
  AuthenticatedAppCheckoutRouteImport.update({
    id: '/app/checkout',
    path: '/app/checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAthletesRoute =
  AuthenticatedAppAthletesRouteImport.update({
    id: '/app/athletes',
    path: '/app/athletes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/app/analytics',
    path: '/app/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSessionsIndexRoute =
  AuthenticatedAppSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSessionsRoute,
  } as any)
const AuthenticatedAppRacesIndexRoute =
  AuthenticatedAppRacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppRacesRoute,
  } as any)
const AuthenticatedAppCoachIndexRoute =
  AuthenticatedAppCoachIndexRouteImport.update({
    id: '/app/coach/',
    path: '/app/coach/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAthletesIndexRoute =
  AuthenticatedAppAthletesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAthletesRoute,
  } as any)
const ApiPublicHooksRunDailyRemindersRoute =
  ApiPublicHooksRunDailyRemindersRouteImport.update({
    id: '/api/public/hooks/run-daily-reminders',
    path: '/api/public/hooks/run-daily-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchPushRoute =
  ApiPublicHooksDispatchPushRouteImport.update({
    id: '/api/public/hooks/dispatch-push',
    path: '/api/public/hooks/dispatch-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSessionsNewRoute =
  AuthenticatedAppSessionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppSessionsRoute,
  } as any)
const AuthenticatedAppSessionsCalendarRoute =
  AuthenticatedAppSessionsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppSessionsRoute,
  } as any)
const AuthenticatedAppSessionsSessionIdRoute =
  AuthenticatedAppSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedAppSessionsRoute,
  } as any)
const AuthenticatedAppRacesRaceIdRoute =
  AuthenticatedAppRacesRaceIdRouteImport.update({
    id: '/$raceId',
    path: '/$raceId',
    getParentRoute: () => AuthenticatedAppRacesRoute,
  } as any)
const AuthenticatedAppCoachSlugRoute =
  AuthenticatedAppCoachSlugRouteImport.update({
    id: '/app/coach/$slug',
    path: '/app/coach/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAthletesAthleteIdRoute =
  AuthenticatedAppAthletesAthleteIdRouteImport.update({
    id: '/$athleteId',
    path: '/$athleteId',
    getParentRoute: () => AuthenticatedAppAthletesRoute,
  } as any)
const AuthenticatedAppSessionsSessionIdIndexRoute =
  AuthenticatedAppSessionsSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSessionsSessionIdRoute,
  } as any)
const AuthenticatedAppRacesRaceIdIndexRoute =
  AuthenticatedAppRacesRaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppRacesRaceIdRoute,
  } as any)
const AuthenticatedAppSessionsSessionIdAnalysisRoute =
  AuthenticatedAppSessionsSessionIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedAppSessionsSessionIdRoute,
  } as any)
const AuthenticatedAppRacesRaceIdAnalysisRoute =
  AuthenticatedAppRacesRaceIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedAppRacesRaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/athletes': typeof AuthenticatedAppAthletesRouteWithChildren
  '/app/checkout': typeof AuthenticatedAppCheckoutRoute
  '/app/daily-log': typeof AuthenticatedAppDailyLogRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/noticeboard': typeof AuthenticatedAppNoticeboardRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/races': typeof AuthenticatedAppRacesRouteWithChildren
  '/app/sessions': typeof AuthenticatedAppSessionsRouteWithChildren
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/athletes/$athleteId': typeof AuthenticatedAppAthletesAthleteIdRoute
  '/app/coach/$slug': typeof AuthenticatedAppCoachSlugRoute
  '/app/races/$raceId': typeof AuthenticatedAppRacesRaceIdRouteWithChildren
  '/app/sessions/$sessionId': typeof AuthenticatedAppSessionsSessionIdRouteWithChildren
  '/app/sessions/calendar': typeof AuthenticatedAppSessionsCalendarRoute
  '/app/sessions/new': typeof AuthenticatedAppSessionsNewRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/hooks/run-daily-reminders': typeof ApiPublicHooksRunDailyRemindersRoute
  '/app/athletes/': typeof AuthenticatedAppAthletesIndexRoute
  '/app/coach/': typeof AuthenticatedAppCoachIndexRoute
  '/app/races/': typeof AuthenticatedAppRacesIndexRoute
  '/app/sessions/': typeof AuthenticatedAppSessionsIndexRoute
  '/app/races/$raceId/analysis': typeof AuthenticatedAppRacesRaceIdAnalysisRoute
  '/app/sessions/$sessionId/analysis': typeof AuthenticatedAppSessionsSessionIdAnalysisRoute
  '/app/races/$raceId/': typeof AuthenticatedAppRacesRaceIdIndexRoute
  '/app/sessions/$sessionId/': typeof AuthenticatedAppSessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/checkout': typeof AuthenticatedAppCheckoutRoute
  '/app/daily-log': typeof AuthenticatedAppDailyLogRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/noticeboard': typeof AuthenticatedAppNoticeboardRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/athletes/$athleteId': typeof AuthenticatedAppAthletesAthleteIdRoute
  '/app/coach/$slug': typeof AuthenticatedAppCoachSlugRoute
  '/app/sessions/calendar': typeof AuthenticatedAppSessionsCalendarRoute
  '/app/sessions/new': typeof AuthenticatedAppSessionsNewRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/hooks/run-daily-reminders': typeof ApiPublicHooksRunDailyRemindersRoute
  '/app/athletes': typeof AuthenticatedAppAthletesIndexRoute
  '/app/coach': typeof AuthenticatedAppCoachIndexRoute
  '/app/races': typeof AuthenticatedAppRacesIndexRoute
  '/app/sessions': typeof AuthenticatedAppSessionsIndexRoute
  '/app/races/$raceId/analysis': typeof AuthenticatedAppRacesRaceIdAnalysisRoute
  '/app/sessions/$sessionId/analysis': typeof AuthenticatedAppSessionsSessionIdAnalysisRoute
  '/app/races/$raceId': typeof AuthenticatedAppRacesRaceIdIndexRoute
  '/app/sessions/$sessionId': typeof AuthenticatedAppSessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/athletes': typeof AuthenticatedAppAthletesRouteWithChildren
  '/_authenticated/app/checkout': typeof AuthenticatedAppCheckoutRoute
  '/_authenticated/app/daily-log': typeof AuthenticatedAppDailyLogRoute
  '/_authenticated/app/messages': typeof AuthenticatedAppMessagesRoute
  '/_authenticated/app/noticeboard': typeof AuthenticatedAppNoticeboardRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/races': typeof AuthenticatedAppRacesRouteWithChildren
  '/_authenticated/app/sessions': typeof AuthenticatedAppSessionsRouteWithChildren
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/_authenticated/app/today': typeof AuthenticatedAppTodayRoute
  '/_authenticated/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/athletes/$athleteId': typeof AuthenticatedAppAthletesAthleteIdRoute
  '/_authenticated/app/coach/$slug': typeof AuthenticatedAppCoachSlugRoute
  '/_authenticated/app/races/$raceId': typeof AuthenticatedAppRacesRaceIdRouteWithChildren
  '/_authenticated/app/sessions/$sessionId': typeof AuthenticatedAppSessionsSessionIdRouteWithChildren
  '/_authenticated/app/sessions/calendar': typeof AuthenticatedAppSessionsCalendarRoute
  '/_authenticated/app/sessions/new': typeof AuthenticatedAppSessionsNewRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
  '/api/public/hooks/run-daily-reminders': typeof ApiPublicHooksRunDailyRemindersRoute
  '/_authenticated/app/athletes/': typeof AuthenticatedAppAthletesIndexRoute
  '/_authenticated/app/coach/': typeof AuthenticatedAppCoachIndexRoute
  '/_authenticated/app/races/': typeof AuthenticatedAppRacesIndexRoute
  '/_authenticated/app/sessions/': typeof AuthenticatedAppSessionsIndexRoute
  '/_authenticated/app/races/$raceId/analysis': typeof AuthenticatedAppRacesRaceIdAnalysisRoute
  '/_authenticated/app/sessions/$sessionId/analysis': typeof AuthenticatedAppSessionsSessionIdAnalysisRoute
  '/_authenticated/app/races/$raceId/': typeof AuthenticatedAppRacesRaceIdIndexRoute
  '/_authenticated/app/sessions/$sessionId/': typeof AuthenticatedAppSessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/claim/$token'
    | '/app/analytics'
    | '/app/athletes'
    | '/app/checkout'
    | '/app/daily-log'
    | '/app/messages'
    | '/app/noticeboard'
    | '/app/profile'
    | '/app/races'
    | '/app/sessions'
    | '/app/templates'
    | '/app/today'
    | '/app/vitals'
    | '/app/'
    | '/app/athletes/$athleteId'
    | '/app/coach/$slug'
    | '/app/races/$raceId'
    | '/app/sessions/$sessionId'
    | '/app/sessions/calendar'
    | '/app/sessions/new'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/hooks/run-daily-reminders'
    | '/app/athletes/'
    | '/app/coach/'
    | '/app/races/'
    | '/app/sessions/'
    | '/app/races/$raceId/analysis'
    | '/app/sessions/$sessionId/analysis'
    | '/app/races/$raceId/'
    | '/app/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/claim/$token'
    | '/app/analytics'
    | '/app/checkout'
    | '/app/daily-log'
    | '/app/messages'
    | '/app/noticeboard'
    | '/app/profile'
    | '/app/templates'
    | '/app/today'
    | '/app/vitals'
    | '/app'
    | '/app/athletes/$athleteId'
    | '/app/coach/$slug'
    | '/app/sessions/calendar'
    | '/app/sessions/new'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/hooks/run-daily-reminders'
    | '/app/athletes'
    | '/app/coach'
    | '/app/races'
    | '/app/sessions'
    | '/app/races/$raceId/analysis'
    | '/app/sessions/$sessionId/analysis'
    | '/app/races/$raceId'
    | '/app/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/claim/$token'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/athletes'
    | '/_authenticated/app/checkout'
    | '/_authenticated/app/daily-log'
    | '/_authenticated/app/messages'
    | '/_authenticated/app/noticeboard'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/races'
    | '/_authenticated/app/sessions'
    | '/_authenticated/app/templates'
    | '/_authenticated/app/today'
    | '/_authenticated/app/vitals'
    | '/_authenticated/app/'
    | '/_authenticated/app/athletes/$athleteId'
    | '/_authenticated/app/coach/$slug'
    | '/_authenticated/app/races/$raceId'
    | '/_authenticated/app/sessions/$sessionId'
    | '/_authenticated/app/sessions/calendar'
    | '/_authenticated/app/sessions/new'
    | '/api/public/hooks/dispatch-push'
    | '/api/public/hooks/run-daily-reminders'
    | '/_authenticated/app/athletes/'
    | '/_authenticated/app/coach/'
    | '/_authenticated/app/races/'
    | '/_authenticated/app/sessions/'
    | '/_authenticated/app/races/$raceId/analysis'
    | '/_authenticated/app/sessions/$sessionId/analysis'
    | '/_authenticated/app/races/$raceId/'
    | '/_authenticated/app/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  ApiPublicHooksDispatchPushRoute: typeof ApiPublicHooksDispatchPushRoute
  ApiPublicHooksRunDailyRemindersRoute: typeof ApiPublicHooksRunDailyRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/vitals': {
      id: '/_authenticated/app/vitals'
      path: '/app/vitals'
      fullPath: '/app/vitals'
      preLoaderRoute: typeof AuthenticatedAppVitalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/today': {
      id: '/_authenticated/app/today'
      path: '/app/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AuthenticatedAppTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/app/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sessions': {
      id: '/_authenticated/app/sessions'
      path: '/app/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AuthenticatedAppSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/races': {
      id: '/_authenticated/app/races'
      path: '/app/races'
      fullPath: '/app/races'
      preLoaderRoute: typeof AuthenticatedAppRacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/noticeboard': {
      id: '/_authenticated/app/noticeboard'
      path: '/app/noticeboard'
      fullPath: '/app/noticeboard'
      preLoaderRoute: typeof AuthenticatedAppNoticeboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/messages': {
      id: '/_authenticated/app/messages'
      path: '/app/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/daily-log': {
      id: '/_authenticated/app/daily-log'
      path: '/app/daily-log'
      fullPath: '/app/daily-log'
      preLoaderRoute: typeof AuthenticatedAppDailyLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/checkout': {
      id: '/_authenticated/app/checkout'
      path: '/app/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AuthenticatedAppCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/athletes': {
      id: '/_authenticated/app/athletes'
      path: '/app/athletes'
      fullPath: '/app/athletes'
      preLoaderRoute: typeof AuthenticatedAppAthletesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sessions/': {
      id: '/_authenticated/app/sessions/'
      path: '/'
      fullPath: '/app/sessions/'
      preLoaderRoute: typeof AuthenticatedAppSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSessionsRoute
    }
    '/_authenticated/app/races/': {
      id: '/_authenticated/app/races/'
      path: '/'
      fullPath: '/app/races/'
      preLoaderRoute: typeof AuthenticatedAppRacesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRacesRoute
    }
    '/_authenticated/app/coach/': {
      id: '/_authenticated/app/coach/'
      path: '/app/coach'
      fullPath: '/app/coach/'
      preLoaderRoute: typeof AuthenticatedAppCoachIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/athletes/': {
      id: '/_authenticated/app/athletes/'
      path: '/'
      fullPath: '/app/athletes/'
      preLoaderRoute: typeof AuthenticatedAppAthletesIndexRouteImport
      parentRoute: typeof AuthenticatedAppAthletesRoute
    }
    '/api/public/hooks/run-daily-reminders': {
      id: '/api/public/hooks/run-daily-reminders'
      path: '/api/public/hooks/run-daily-reminders'
      fullPath: '/api/public/hooks/run-daily-reminders'
      preLoaderRoute: typeof ApiPublicHooksRunDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-push': {
      id: '/api/public/hooks/dispatch-push'
      path: '/api/public/hooks/dispatch-push'
      fullPath: '/api/public/hooks/dispatch-push'
      preLoaderRoute: typeof ApiPublicHooksDispatchPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/sessions/new': {
      id: '/_authenticated/app/sessions/new'
      path: '/new'
      fullPath: '/app/sessions/new'
      preLoaderRoute: typeof AuthenticatedAppSessionsNewRouteImport
      parentRoute: typeof AuthenticatedAppSessionsRoute
    }
    '/_authenticated/app/sessions/calendar': {
      id: '/_authenticated/app/sessions/calendar'
      path: '/calendar'
      fullPath: '/app/sessions/calendar'
      preLoaderRoute: typeof AuthenticatedAppSessionsCalendarRouteImport
      parentRoute: typeof AuthenticatedAppSessionsRoute
    }
    '/_authenticated/app/sessions/$sessionId': {
      id: '/_authenticated/app/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/app/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedAppSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedAppSessionsRoute
    }
    '/_authenticated/app/races/$raceId': {
      id: '/_authenticated/app/races/$raceId'
      path: '/$raceId'
      fullPath: '/app/races/$raceId'
      preLoaderRoute: typeof AuthenticatedAppRacesRaceIdRouteImport
      parentRoute: typeof AuthenticatedAppRacesRoute
    }
    '/_authenticated/app/coach/$slug': {
      id: '/_authenticated/app/coach/$slug'
      path: '/app/coach/$slug'
      fullPath: '/app/coach/$slug'
      preLoaderRoute: typeof AuthenticatedAppCoachSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/athletes/$athleteId': {
      id: '/_authenticated/app/athletes/$athleteId'
      path: '/$athleteId'
      fullPath: '/app/athletes/$athleteId'
      preLoaderRoute: typeof AuthenticatedAppAthletesAthleteIdRouteImport
      parentRoute: typeof AuthenticatedAppAthletesRoute
    }
    '/_authenticated/app/sessions/$sessionId/': {
      id: '/_authenticated/app/sessions/$sessionId/'
      path: '/'
      fullPath: '/app/sessions/$sessionId/'
      preLoaderRoute: typeof AuthenticatedAppSessionsSessionIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppSessionsSessionIdRoute
    }
    '/_authenticated/app/races/$raceId/': {
      id: '/_authenticated/app/races/$raceId/'
      path: '/'
      fullPath: '/app/races/$raceId/'
      preLoaderRoute: typeof AuthenticatedAppRacesRaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppRacesRaceIdRoute
    }
    '/_authenticated/app/sessions/$sessionId/analysis': {
      id: '/_authenticated/app/sessions/$sessionId/analysis'
      path: '/analysis'
      fullPath: '/app/sessions/$sessionId/analysis'
      preLoaderRoute: typeof AuthenticatedAppSessionsSessionIdAnalysisRouteImport
      parentRoute: typeof AuthenticatedAppSessionsSessionIdRoute
    }
    '/_authenticated/app/races/$raceId/analysis': {
      id: '/_authenticated/app/races/$raceId/analysis'
      path: '/analysis'
      fullPath: '/app/races/$raceId/analysis'
      preLoaderRoute: typeof AuthenticatedAppRacesRaceIdAnalysisRouteImport
      parentRoute: typeof AuthenticatedAppRacesRaceIdRoute
    }
  }
}

interface AuthenticatedAppAthletesRouteChildren {
  AuthenticatedAppAthletesAthleteIdRoute: typeof AuthenticatedAppAthletesAthleteIdRoute
  AuthenticatedAppAthletesIndexRoute: typeof AuthenticatedAppAthletesIndexRoute
}

const AuthenticatedAppAthletesRouteChildren: AuthenticatedAppAthletesRouteChildren =
  {
    AuthenticatedAppAthletesAthleteIdRoute:
      AuthenticatedAppAthletesAthleteIdRoute,
    AuthenticatedAppAthletesIndexRoute: AuthenticatedAppAthletesIndexRoute,
  }

const AuthenticatedAppAthletesRouteWithChildren =
  AuthenticatedAppAthletesRoute._addFileChildren(
    AuthenticatedAppAthletesRouteChildren,
  )

interface AuthenticatedAppRacesRaceIdRouteChildren {
  AuthenticatedAppRacesRaceIdAnalysisRoute: typeof AuthenticatedAppRacesRaceIdAnalysisRoute
  AuthenticatedAppRacesRaceIdIndexRoute: typeof AuthenticatedAppRacesRaceIdIndexRoute
}

const AuthenticatedAppRacesRaceIdRouteChildren: AuthenticatedAppRacesRaceIdRouteChildren =
  {
    AuthenticatedAppRacesRaceIdAnalysisRoute:
      AuthenticatedAppRacesRaceIdAnalysisRoute,
    AuthenticatedAppRacesRaceIdIndexRoute:
      AuthenticatedAppRacesRaceIdIndexRoute,
  }

const AuthenticatedAppRacesRaceIdRouteWithChildren =
  AuthenticatedAppRacesRaceIdRoute._addFileChildren(
    AuthenticatedAppRacesRaceIdRouteChildren,
  )

interface AuthenticatedAppRacesRouteChildren {
  AuthenticatedAppRacesRaceIdRoute: typeof AuthenticatedAppRacesRaceIdRouteWithChildren
  AuthenticatedAppRacesIndexRoute: typeof AuthenticatedAppRacesIndexRoute
}

const AuthenticatedAppRacesRouteChildren: AuthenticatedAppRacesRouteChildren = {
  AuthenticatedAppRacesRaceIdRoute:
    AuthenticatedAppRacesRaceIdRouteWithChildren,
  AuthenticatedAppRacesIndexRoute: AuthenticatedAppRacesIndexRoute,
}

const AuthenticatedAppRacesRouteWithChildren =
  AuthenticatedAppRacesRoute._addFileChildren(
    AuthenticatedAppRacesRouteChildren,
  )

interface AuthenticatedAppSessionsSessionIdRouteChildren {
  AuthenticatedAppSessionsSessionIdAnalysisRoute: typeof AuthenticatedAppSessionsSessionIdAnalysisRoute
  AuthenticatedAppSessionsSessionIdIndexRoute: typeof AuthenticatedAppSessionsSessionIdIndexRoute
}

const AuthenticatedAppSessionsSessionIdRouteChildren: AuthenticatedAppSessionsSessionIdRouteChildren =
  {
    AuthenticatedAppSessionsSessionIdAnalysisRoute:
      AuthenticatedAppSessionsSessionIdAnalysisRoute,
    AuthenticatedAppSessionsSessionIdIndexRoute:
      AuthenticatedAppSessionsSessionIdIndexRoute,
  }

const AuthenticatedAppSessionsSessionIdRouteWithChildren =
  AuthenticatedAppSessionsSessionIdRoute._addFileChildren(
    AuthenticatedAppSessionsSessionIdRouteChildren,
  )

interface AuthenticatedAppSessionsRouteChildren {
  AuthenticatedAppSessionsSessionIdRoute: typeof AuthenticatedAppSessionsSessionIdRouteWithChildren
  AuthenticatedAppSessionsCalendarRoute: typeof AuthenticatedAppSessionsCalendarRoute
  AuthenticatedAppSessionsNewRoute: typeof AuthenticatedAppSessionsNewRoute
  AuthenticatedAppSessionsIndexRoute: typeof AuthenticatedAppSessionsIndexRoute
}

const AuthenticatedAppSessionsRouteChildren: AuthenticatedAppSessionsRouteChildren =
  {
    AuthenticatedAppSessionsSessionIdRoute:
      AuthenticatedAppSessionsSessionIdRouteWithChildren,
    AuthenticatedAppSessionsCalendarRoute:
      AuthenticatedAppSessionsCalendarRoute,
    AuthenticatedAppSessionsNewRoute: AuthenticatedAppSessionsNewRoute,
    AuthenticatedAppSessionsIndexRoute: AuthenticatedAppSessionsIndexRoute,
  }

const AuthenticatedAppSessionsRouteWithChildren =
  AuthenticatedAppSessionsRoute._addFileChildren(
    AuthenticatedAppSessionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppAthletesRoute: typeof AuthenticatedAppAthletesRouteWithChildren
  AuthenticatedAppCheckoutRoute: typeof AuthenticatedAppCheckoutRoute
  AuthenticatedAppDailyLogRoute: typeof AuthenticatedAppDailyLogRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRoute
  AuthenticatedAppNoticeboardRoute: typeof AuthenticatedAppNoticeboardRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRacesRoute: typeof AuthenticatedAppRacesRouteWithChildren
  AuthenticatedAppSessionsRoute: typeof AuthenticatedAppSessionsRouteWithChildren
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRoute
  AuthenticatedAppTodayRoute: typeof AuthenticatedAppTodayRoute
  AuthenticatedAppVitalsRoute: typeof AuthenticatedAppVitalsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCoachSlugRoute: typeof AuthenticatedAppCoachSlugRoute
  AuthenticatedAppCoachIndexRoute: typeof AuthenticatedAppCoachIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppAthletesRoute: AuthenticatedAppAthletesRouteWithChildren,
  AuthenticatedAppCheckoutRoute: AuthenticatedAppCheckoutRoute,
  AuthenticatedAppDailyLogRoute: AuthenticatedAppDailyLogRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRoute,
  AuthenticatedAppNoticeboardRoute: AuthenticatedAppNoticeboardRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRacesRoute: AuthenticatedAppRacesRouteWithChildren,
  AuthenticatedAppSessionsRoute: AuthenticatedAppSessionsRouteWithChildren,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRoute,
  AuthenticatedAppTodayRoute: AuthenticatedAppTodayRoute,
  AuthenticatedAppVitalsRoute: AuthenticatedAppVitalsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCoachSlugRoute: AuthenticatedAppCoachSlugRoute,
  AuthenticatedAppCoachIndexRoute: AuthenticatedAppCoachIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  ApiPublicHooksDispatchPushRoute: ApiPublicHooksDispatchPushRoute,
  ApiPublicHooksRunDailyRemindersRoute: ApiPublicHooksRunDailyRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
